[main]
include=realtime-virtual-host
summary=Welotec custom for RT host

[variables]
isolated_cores=1-7
non_isolated_cores=0
non_isolated_cores_expanded=${f:cpulist_unpack:${non_isolated_cores}}

[sysctl]
kernel.printk=3 1 1 7

[sysfs]
/sys/module/kvm/parameters/halt_poll_ns = 0

[bootloader]
cmdline_realtime=-
cmdline_wrt=+processor.max_cstate=1 intel_idle.max_cstate=1 cpufreq.default_governor=performance rcu_nocb_poll default_hugepagesz=1GB hugepagesz=1GB hugepages=16 ipv6.disable=1 audit=0 iomem=relaxed intel_iommu=on iommu=pt intel_pstate=passive intel_pstate.no_hwp=1 isolcpus=${managed_irq}${isolated_cores} nosoftlockup

[systemd]
disable=pmie.service pmie_farm.service pmie_check.timer pmie_daily.timer pmie_farm_check.timer
stop=pmie.service pmie_farm.service pmie_check.timer pmie_daily.timer pmie_farm_check.timer
enable=cpu_setup.service nic_setup.service
start=cpu_setup.service nic_setup.service

[script]
script=/etc/tuned/welo-rt/irqbalance_modifier.sh

[scheduler]
# for i in `pgrep rcuc` ; do grep Cpus_allowed_list /proc/$i/status ; done
group.rcuc=0:f:10:*:^\[rcuc
